### PR TITLE
Install instructions for Debian wheezy

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by tcatm** [comment]
You can just use the python3.4 package from Debian 7.

**Comment by rubo77** [comment]
unfortunately there is no python3.4 packet in wheezy
and installed is 3.2

    apt-cache show python3|grep Version
    Version: 3.2.3-6

**Comment by tcatm** [comment]
Are you going to include the suggestions I made in #gluon?

**Comment by rubo77** [comment]
I adapted it a bit like https://github.com/ffnord/ffmap-backend/blob/master/README.md but there is not much similarity to find.

Maybe you can close this PR and use my suggestion as a start for a README with some more background-knowledge.

**Pull request closed without merging**
